apiVersion: v1
kind: Service
metadata:
    name: mbodagaladockerdotnetcorepoc
spec:
    type: LoadBalancer
    ports:
    - port: 8085 
    selector:
        app: mbodagaladockerdotnetcorepoc